### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by Ambrevar** [walseb/blimp#6]
The GPL license file is missing.

**Comment by walseb** [comment]
Isn't it enough to just refer to the emacs copy or an online copy? I have this in `blimp.el`
```
;; You should have received a copy of the GNU General Public License
;; along with GNU Emacs.  If not, see <http://www.gnu.org/licenses/>.
```

**Comment by Ambrevar** [comment]
It's not recommended.  See
https://www.gnu.org/licenses/gpl-faq.html#WhyMustIInclude.

**Comment by walseb** [comment]
Fixed!
